export const STAFFS_LANGUAGE_SET = {
  ENGLISH: "Staffs",
  HINDI: "स्टाफ",
  MARATHI: "स्टाफ",
  BENGALI: "স্টাফ",
  GUJARATI: "સ્ટાફ",
  TAMIL: "ஸ்டாஃப்",
  TELUGU: "స్టాఫ్",
  MALYALI: "സ്റ്റാഫ്",
  KANNADA: "ಸ್ಟಾಫ್",
};

export const TABLES_LANGUAGE_SET = {
  ENGLISH: "Tables",
  HINDI: "टेबल",
  MARATHI: "टेबल",
  BENGALI: "টেবিল",
  GUJARATI: "ટેબલ",
  TAMIL: "டேபிள்",
  TELUGU: "టేబుల్",
  MALYALI: "ടേബിള്‍",
  KANNADA: "ಟೇಬಲ್",
};

export const MENU_LANGUAGE_SET = {
  ENGLISH: "Menu",
  HINDI: "मेनू",
  MARATHI: "मेनू",
  BENGALI: "মেনু",
  GUJARATI: "મેનૂ",
  TAMIL: "மெனு",
  TELUGU: "మెను",
  MALYALI: "മെനു",
  KANNADA: "ಮೆನು",
};

export const ORDERS_LANGUAGE_SET = {
  ENGLISH: "Orders",
  HINDI: "ऑर्डर",
  MARATHI: "ऑर्डर",
  BENGALI: "অর্ডার",
  GUJARATI: "ઓર્ડર",
  TAMIL: "ஆர்டர்",
  TELUGU: "ఆర్డర్",
  MALYALI: "ഓർഡർ",
  KANNADA: "ಆರ್ಡರ್",
};

export const INVENTORY_LANGUAGE_SET = {
  ENGLISH: "Inventory",
  HINDI: "इन्वेंटरी",
  MARATHI: "इन्वेंटरी",
  BENGALI: "ইনভেন্টরি",
  GUJARATI: "ઇન્વેન્ટરી",
  TAMIL: "இன்வெண்டரி",
  TELUGU: "ఇన్వెంటరీ",
  MALYALI: "ഇൻവെന്ററി",
  KANNADA: "ಇನ್ವೆಂಟರಿ",
};

export const PROFILE_LANGUAGE_SET = {
  ENGLISH: "Profile",
  HINDI: "प्रोफ़ाइल",
  MARATHI: "प्रोफाइल",
  BENGALI: "প্রোফাইল",
  GUJARATI: "પ્રોફાઇલ",
  TAMIL: "ப்ரொஃபைல்",
  TELUGU: "ప్రొఫైల్",
  MALYALI: "പ്രൊഫൈൽ",
  KANNADA: "ಪ್ರೊಫೈಲ್",
};

export const OVERVIEW_LANGUAGE_SET = {
  ENGLISH: "Today's Overview",
  HINDI: "आज का हाल",
  MARATHI: "आजचा आढावा",
  BENGALI: "আজকের সারাংশ",
  GUJARATI: "આજની સ્થિતિ",
  TAMIL: "இன்றைய நிலைமைகள்",
  TELUGU: "ఈరోజు సమీక్ష",
  MALYALI: "ഇന്നത്തെ അവലോകനം",
  KANNADA: "ಇಂದಿನ ಸ್ಥಿತಿ",
};

export const OVERVIEW_ITEMS_LANGUAGE_SET = {
  ACTIVE_TABLES: {
    ENGLISH: "Active Table",
    HINDI: "चालू टेबल",
    MARATHI: "चालू टेबल",
    BENGALI: "চলমান টেবিল",
    GUJARATI: "ચાલુ ટેબલ",
    TAMIL: "நடப்பில் உள்ள டேபிள்கள்",
    TELUGU: "నడుస్తున్న టేబుల్స్",
    MALYALI: "നിലവിലുള്ള ടേബിള്‍",
    KANNADA: "ಚಾಲ್ತಿಯಲ್ಲಿರುವ ಟೇಬಲ್",
  },
  ACTIVE_ORDERS: {
    ENGLISH: "Active Orders",
    HINDI: "चालू ऑर्डर",
    MARATHI: "चालू ऑर्डर",
    BENGALI: "চলমান অর্ডার",
    GUJARATI: "ચાલુ ઑર્ડર",
    TAMIL: "நடப்பில் உள்ள ஆர்டர்கள்",
    TELUGU: "నడుస్తున్న ఆర్డర్లు",
    MALYALI: "നിലവിലുള്ള ഓര്‍ഡറുകൾ",
    KANNADA: "ಚಾಲ್ತಿಯಲ್ಲಿರುವ ಆರ್ಡರ್",
  },
  CLOSED_ORDERS: {
    ENGLISH: "Complete Orders",
    HINDI: "पूर्ण ऑर्डर",
    MARATHI: "पूर्ण ऑर्डर",
    BENGALI: "সম্পূর্ণ অর্ডার",
    GUJARATI: "પૂર્ણ ઓર્ડર્સ",
    TAMIL: "முழுமையான ஆர்டர்கள்",
    TELUGU: "పూర్తి ఆర్డర్లు",
    MALYALI: "പൂർത്തിയായ ഓർഡറുകൾ",
    KANNADA: "ಪೂರ್ಣ ಆರ್ಡರ್",
  },
  TODAYS_REVENUE: {
    ENGLISH: "Today's Revenue",
    HINDI: "आज की आय",
    MARATHI: "आजचे उत्पन्न",
    BENGALI: "আজকের রাজস্ব",
    GUJARATI: "આજે આવક",
    TAMIL: "இன்றைய வருமானம் ",
    TELUGU: "ఈ రోజు ఆదాయం ",
    MALYALI: "ഇന്നത്തെ വരുമാനം ",
    KANNADA: "ಇಂದಿನ ಆದಾಯ",
  },
  LAST_7_DAYS_REV: {
    ENGLISH: "Last 7 days rev",
    HINDI: "7 दिन का आय",
    MARATHI: "7 दिवस आय",
    BENGALI: "7 দিন আয়",
    GUJARATI: "7 દિવસ આવક",
    TAMIL: "7 நாள் வருவாய்",
    TELUGU: "7 రోజుల ఆదాయం",
    MALYALI: "7 ദിവസ വരുമാനം",
    KANNADA: "7 ದಿನ ಆದಾಯ",
  },
  LAST_DAY_REV: {
    ENGLISH: "Last day rev",
    HINDI: "कल का आय",
    MARATHI: "कालचे उत्पन्न",
    BENGALI: "গতকালের আয়",
    GUJARATI: "ગઈકાલની આવક",
    TAMIL: "நேற்று வருமானம்",
    TELUGU: "నిన్న ఆదాయం",
    MALYALI: "ഇന്നലെ വരുമാനം",
    KANNADA: "ನಿನ್ನೆಯ ಆದಾಯ",
  },
};
