export const STAFFS_LANGUAGE_SET = {
  ENGLISH: "Staffs",
  HINDI: "स्टाफ",
  MARATHI: "स्टाफ",
  BENGALI: "স্টাফ",
  GUJARATI: "સ્ટાફ",
  TAMIL: "ஸ்டாஃப்",
  TELUGU: "స్టాఫ్",
  MALYALI: "സ്റ്റാഫ്",
  KANNADA: "ಸ್ಟಾಫ್",
};

export const TABLES_LANGUAGE_SET = {
  ENGLISH: "Tables",
  HINDI: "टेबल",
  MARATHI: "टेबल",
  BENGALI: "টেবিল",
  GUJARATI: "ટેબલ",
  TAMIL: "டேபிள்",
  TELUGU: "టేబుల్",
  MALYALI: "ടേബിള്‍",
  KANNADA: "ಟೇಬಲ್",
};

export const MENU_LANGUAGE_SET = {
  ENGLISH: "Menu",
  HINDI: "मेनू",
  MARATHI: "मेनू",
  BENGALI: "মেনু",
  GUJARATI: "મેનૂ",
  TAMIL: "மெனு",
  TELUGU: "మెను",
  MALYALI: "മെനു",
  KANNADA: "ಮೆನು",
};

export const ORDERS_LANGUAGE_SET = {
  ENGLISH: "Orders",
  HINDI: "ऑर्डर",
  MARATHI: "ऑर्डर",
  BENGALI: "অর্ডার",
  GUJARATI: "ઓર્ડર",
  TAMIL: "ஆர்டர்",
  TELUGU: "ఆర్డర్",
  MALYALI: "ഓർഡർ",
  KANNADA: "ಆರ್ಡರ್",
};

export const INVENTORY_LANGUAGE_SET = {
  ENGLISH: "Inventory",
  HINDI: "इन्वेंटरी",
  MARATHI: "इन्वेंटरी",
  BENGALI: "ইনভেন্টরি",
  GUJARATI: "ઇન્વેન્ટરી",
  TAMIL: "இன்வெண்டரி",
  TELUGU: "ఇన్వెంటరీ",
  MALYALI: "ഇൻവെന്ററി",
  KANNADA: "ಇನ್ವೆಂಟರಿ",
};

export const PROFILE_LANGUAGE_SET = {
  ENGLISH: "Profile",
  HINDI: "प्रोफ़ाइल",
  MARATHI: "प्रोफाइल",
  BENGALI: "প্রোফাইল",
  GUJARATI: "પ્રોફાઇલ",
  TAMIL: "ப்ரொஃபைல்",
  TELUGU: "ప్రొఫైల్",
  MALYALI: "പ്രൊഫൈൽ",
  KANNADA: "ಪ್ರೊಫೈಲ್",
};

export const OVERVIEW_LANGUAGE_SET = {
  ENGLISH: "Today's Overview",
  HINDI: "आज का हाल",
  MARATHI: "आजचा आढावा",
  BENGALI: "আজকের সারাংশ",
  GUJARATI: "આજની સ્થિતિ",
  TAMIL: "இன்றைய நிலைமைகள்",
  TELUGU: "ఈరోజు సమీక్ష",
  MALYALI: "ഇന്നത്തെ അവലോകനം",
  KANNADA: "ಇಂದಿನ ಸ್ಥಿತಿ",
};

export const OVERVIEW_ITEMS_LANGUAGE_SET = {
  ACTIVE_TABLES: {
    ENGLISH: "Active Bookings",
    HINDI: "सक्रिय बुकिंग",
    MARATHI: "सक्रिय बुकिंग",
    BENGALI: "সক্রিয় বুকিং",
    GUJARATI: "સક્રિય બુકિંગ",
    TAMIL: "செயலில் உள்ள முன்பதிவுகள்",
    TELUGU: "చురుకైన బుకింగ్‌లు",
    MALYALI: "സജീവ ബുക്കിംഗുകൾ",
    KANNADA: "ಸಕ್ರಿಯ ಬುಕಿಂಗ್‌ಗಳು",
  },
  ACTIVE_ORDERS: {
    ENGLISH: "Active Orders",
    HINDI: "चालू ऑर्डर",
    MARATHI: "चालू ऑर्डर",
    BENGALI: "চলমান অর্ডার",
    GUJARATI: "ચાલુ ઑર્ડર",
    TAMIL: "நடப்பில் உள்ள ஆர்டர்கள்",
    TELUGU: "నడుస్తున్న ఆర్డర్లు",
    MALYALI: "നിലവിലുള്ള ഓര്‍ഡറുകൾ",
    KANNADA: "ಚಾಲ್ತಿಯಲ್ಲಿರುವ ಆರ್ಡರ್",
  },
  IN_KITCHEN_ORDERS: {
    ENGLISH: "Orders in kitchen",
    HINDI: "किचन में ऑर्डर",
    MARATHI: "किचन मध्ये ऑर्डर",
    BENGALI: "কিচেনে অর্ডার",
    GUJARATI: "કિચનમાં ઓર્ડર",
    TAMIL: "கிச்சனில் ஆர்டர்கள்",
    TELUGU: "కిచెన్‌లో ఆర్డర్లు",
    MALYALI: "കിച്ചണിലെ ഓർഡറുകൾ",
    KANNADA: "ಕಿಚನ್‌ನಲ್ಲಿ ಆರ್ಡರ್",
  },
  PENDING_ORDERS: {
    ENGLISH: "Pending Orders",
    HINDI: "लंबित ऑर्डर",
    MARATHI: "प्रलंबित ऑर्डर",
    BENGALI: "অপেক্ষমান অর্ডার",
    GUJARATI: "બાકી ઓર્ડર",
    TAMIL: "நிலுவையில் உள்ள ஆர்டர்கள்",
    TELUGU: "పెండింగ్ ఆర్డర్లు",
    MALYALI: "കാത്തിരിക്കുന്ന ഓർഡറുകൾ",
    KANNADA: "ಬಾಕಿ ಇರುವ ಆರ್ಡರ್‌ಗಳು",
  },
  COMPLETED_BOOKINGS: {
    ENGLISH: "Completed Bookings",
    HINDI: "पूरी हुई बुकिंग",
    MARATHI: "पूर्ण झालेली बुकिंग",
    BENGALI: "সম্পন্ন বুকিং",
    GUJARATI: "પૂર્ણ થયેલ બુકિંગ",
    TAMIL: "முடிக்கப்பட்ட முன்பதிவுகள்",
    TELUGU: "పూర్తయిన బుకింగ్‌లు",
    MALYALI: "പൂർത്തിയാക്കിയ ബുക്കിംഗുകൾ",
    KANNADA: "ಪೂರ್ಣಗೊಂಡ ಬುಕಿಂಗ್‌ಗಳು",
  },
  REVENUE_TODAY: {
    ENGLISH: "Today's revenue",
    HINDI: "आज का आय",
    MARATHI: "आजचे उत्पन्न",
    BENGALI: "আজকের রাজস্ব",
    GUJARATI: "આજની આવક",
    TAMIL: "இன்றைய வருவாய்",
    TELUGU: "ఈరోజు ఆదాయం",
    MALYALI: "ഇന്നത്തെ വരുമാനം",
    KANNADA: "ಇಂದಿನ ಆದಾಯ",
  },
};
